spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: ${SERVER_PORT}
storage:
  strategy: ${STORAGE_STRATEGY}
  path: ${STORAGE_PATH}
  url: ${STORAGE_URL}
  user: ${STORAGE_USER}
  password: ${STORAGE_PASSWORD}

